import type { AppConfig } from '../config.js';
import type { DetectedAssets } from '../flutter/assets.js';
import { type FontMap, fontsToPubspecBlock } from '../flutter/fonts.js';
import type { LegalConfig } from '../flutter/legal.js';

export interface PubspecYamlOptions {
  assets?: DetectedAssets;
  fonts?: FontMap;
  legal?: LegalConfig;
}

export const pubspecYaml = (
  config: AppConfig,
  extraDeps: string[] = [],
  options: PubspecYamlOptions = {},
): string => {
  const assets: DetectedAssets = options.assets ?? {};
  const fonts: FontMap = options.fonts ?? {};
  const legal: LegalConfig = options.legal ?? { privacy: false, terms: false };

  const name = config.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const flutterVersion = config.flutterVersion ?? '>=3.0.0';

  const configDepLines = Object.entries(config.dependencies ?? {}).map(
    ([pkg, ver]) => `  ${pkg}: ${ver}`,
  );

  const extraDepLines = extraDeps.map((dep) => `  ${dep}`);

  const allDepKeys = new Set<string>();
  const mergedDepLines: string[] = [];

  for (const line of [...configDepLines, ...extraDepLines]) {
    const key = line.trim().split(':')[0];
    if (!allDepKeys.has(key)) {
      allDepKeys.add(key);
      mergedDepLines.push(line);
    }
  }

  const depsBlock =
    mergedDepLines.length > 0 ? mergedDepLines.join('\n') + '\n' : '';

  const userAssets = config.assets ?? [];
  const legalAssets: string[] = [];
  if (legal.privacy) legalAssets.push('assets/legal/privacy.md');
  if (legal.terms) legalAssets.push('assets/legal/terms.md');
  const allAssets = [...userAssets, ...legalAssets];

  const assetsSection =
    allAssets.length > 0
      ? `  assets:\n${allAssets.map((a) => `    - ${a}`).join('\n')}\n`
      : '';

  const fontsSection = fontsToPubspecBlock(fonts);

  const hasLauncher = Boolean(assets.icon);
  const hasSplash = Boolean(assets.splash) || Boolean(assets.icon);

  const devDepsExtra: string[] = [];
  if (hasLauncher) devDepsExtra.push('  flutter_launcher_icons: ^0.14.1');
  if (hasSplash) devDepsExtra.push('  flutter_native_splash: ^2.4.3');
  const extraDevBlock =
    devDepsExtra.length > 0 ? devDepsExtra.join('\n') + '\n' : '';

  const bgPath = assets.background
    ? "'.fsx-assets/icons/background.png'"
    : "'#ffffff'";
  const bgKey = assets.background ? 'background_image' : 'color';

  const launcherBlock = hasLauncher
    ? [
        'flutter_launcher_icons:',
        "  image_path: '.fsx-assets/icons/icon.png'",
        '  android: true',
        '  ios: true',
        '  web:',
        '    generate: true',
        "    image_path: '.fsx-assets/icons/icon.png'",
        '  macos:',
        '    generate: true',
        "    image_path: '.fsx-assets/icons/icon.png'",
        '  windows:',
        '    generate: true',
        "    image_path: '.fsx-assets/icons/icon.png'",
        `  adaptive_icon_foreground: '.fsx-assets/icons/icon.png'`,
        `  adaptive_icon_background: ${bgPath}`,
        ...(assets.monochrome
          ? [`  adaptive_icon_monochrome: '.fsx-assets/icons/monochrome.png'`]
          : []),
        ...(assets.iconDark
          ? [`  image_path_dark: '.fsx-assets/icons/dark/icon.png'`]
          : []),
        ...(assets.backgroundDark
          ? [
              `  adaptive_icon_background_dark: '.fsx-assets/icons/dark/background.png'`,
            ]
          : []),
        ...(assets.monochromeDark
          ? [
              `  adaptive_icon_monochrome_dark: '.fsx-assets/icons/dark/monochrome.png'`,
            ]
          : []),
      ].join('\n') + '\n'
    : '';

  const splashImagePath = assets.splash
    ? "'.fsx-assets/icons/splash.png'"
    : "'.fsx-assets/icons/icon.png'";

  const splashBlock = hasSplash
    ? [
        'flutter_native_splash:',
        `  image: ${splashImagePath}`,
        `  ${bgKey}: ${bgPath}`,
        '  android: true',
        '  ios: true',
        '  web: true',
        ...(assets.splashDark
          ? [`  image_dark: '.fsx-assets/icons/dark/splash.png'`]
          : []),
        ...(assets.backgroundDark
          ? [`  background_image_dark: '.fsx-assets/icons/dark/background.png'`]
          : []),
      ].join('\n') + '\n'
    : '';

  return `name: ${name}
description: Generated by flutter.tsx
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '${flutterVersion}'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
${depsBlock}
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
${extraDevBlock}
flutter:
  uses-material-design: true
${assetsSection}${fontsSection}${launcherBlock}${splashBlock}`;
};
