import type { AppConfig } from '../../types/app-toml.js';

export const pubspecYaml = (
  config: AppConfig,
  extraDeps: string[] = [],
): string => {
  const name = config.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const flutterVersion = config.flutterVersion ?? '>=3.0.0';

  const configDepLines = Object.entries(config.dependencies ?? {}).map(
    ([pkg, ver]) => `  ${pkg}: ${ver}`,
  );

  const extraDepLines = extraDeps.map((dep) => `  ${dep}`);

  const allDepKeys = new Set<string>();
  const mergedDepLines: string[] = [];

  for (const line of [...configDepLines, ...extraDepLines]) {
    const key = line.trim().split(':')[0];
    if (!allDepKeys.has(key)) {
      allDepKeys.add(key);
      mergedDepLines.push(line);
    }
  }

  const depsBlock =
    mergedDepLines.length > 0 ? mergedDepLines.join('\n') + '\n' : '';

  const assetsSection =
    config.assets && config.assets.length > 0
      ? `  assets:\n${config.assets.map((a) => `    - ${a}`).join('\n')}\n`
      : '';

  return `name: ${name}
description: Generated by flutter.tsx
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '${flutterVersion}'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
${depsBlock}
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
${assetsSection}`;
};
