import type { AppConfig } from '../../types/app-toml.js';

export const pubspecYaml = (config: AppConfig): string => {
  const name = config.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const flutterVersion = config.flutterVersion ?? '>=3.0.0';

  const extraDeps = Object.entries(config.dependencies ?? {})
    .map(([pkg, ver]) => `  ${pkg}: ${ver}`)
    .join('\n');

  return `name: ${name}
description: Generated by flutter.tsx
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '${flutterVersion}'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
${extraDeps ? extraDeps + '\n' : ''}
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
`;
};
