// DO NOT EDIT — generated by `fsx define`
import type {
  AboutListTileProps,
  AboutDialogProps,
  LicensePageProps,
  BackButtonIconProps,
  BackButtonProps,
  CloseButtonIconProps,
  CloseButtonProps,
  DrawerButtonIconProps,
  DrawerButtonProps,
  EndDrawerButtonIconProps,
  EndDrawerButtonProps,
  ActionChipProps,
  ActionIconThemeProps,
  AdaptiveTextSelectionToolbarProps,
  AnimatedIconProps,
  MaterialAppProps,
  AppBarProps,
  SliverAppBarProps,
  AppBarThemeProps,
  AutocompleteProps,
  BadgeProps,
  BadgeThemeProps,
  MaterialBannerProps,
  MaterialBannerThemeProps,
  BottomAppBarProps,
  BottomAppBarThemeProps,
  BottomNavigationBarProps,
  BottomNavigationBarThemeProps,
  BottomSheetProps,
  RawMaterialButtonProps,
  ButtonBarProps,
  ButtonBarThemeProps,
  ButtonThemeProps,
  CalendarDatePickerProps,
  YearPickerProps,
  CardProps,
  CardThemeProps,
  CarouselViewProps,
  CarouselViewThemeProps,
  CheckboxProps,
  CheckboxListTileProps,
  CheckboxThemeProps,
  ChipProps,
  RawChipProps,
  ChipThemeProps,
  ChoiceChipProps,
  CircleAvatarProps,
  DataTableProps,
  TableRowInkWellProps,
  DataTableThemeProps,
  DatePickerDialogProps,
  DateRangePickerDialogProps,
  DatePickerThemeProps,
  DesktopTextSelectionToolbarProps,
  DesktopTextSelectionToolbarButtonProps,
  DialogProps,
  AlertDialogProps,
  SimpleDialogOptionProps,
  SimpleDialogProps,
  DialogThemeProps,
  DividerProps,
  VerticalDividerProps,
  DividerThemeProps,
  DrawerProps,
  DrawerControllerProps,
  DrawerHeaderProps,
  DrawerThemeProps,
  DropdownMenuItemProps,
  DropdownButtonHideUnderlineProps,
  DropdownButtonProps,
  DropdownButtonFormFieldProps,
  DropdownMenuProps,
  DropdownMenuFormFieldProps,
  DropdownMenuThemeProps,
  ElevatedButtonProps,
  ElevatedButtonThemeProps,
  ExpandIconProps,
  ExpansionPanelListProps,
  ExpansionTileProps,
  ExpansionTileThemeProps,
  FilledButtonProps,
  FilledButtonThemeProps,
  FilterChipProps,
  FlexibleSpaceBarProps,
  FlexibleSpaceBarSettingsProps,
  FloatingActionButtonProps,
  FloatingActionButtonThemeProps,
  GridTileProps,
  GridTileBarProps,
  IconButtonProps,
  IconButtonThemeProps,
  InkProps,
  InkResponseProps,
  InkWellProps,
  InputChipProps,
  InputDatePickerFormFieldProps,
  InputDecoratorProps,
  InputDecorationThemeProps,
  ListTileProps,
  ListTileThemeProps,
  TextMagnifierProps,
  MagnifierProps,
  MaterialProps,
  MaterialButtonProps,
  MenuAnchorProps,
  MenuBarProps,
  MenuItemButtonProps,
  CheckboxMenuButtonProps,
  RadioMenuButtonProps,
  SubmenuButtonProps,
  MenuAcceleratorCallbackBindingProps,
  MenuAcceleratorLabelProps,
  MenuBarThemeProps,
  MenuButtonThemeProps,
  MenuThemeProps,
  MergeableMaterialProps,
  NavigationBarProps,
  NavigationDestinationProps,
  NavigationIndicatorProps,
  NavigationBarThemeProps,
  NavigationDrawerProps,
  NavigationDrawerDestinationProps,
  NavigationDrawerThemeProps,
  NavigationRailProps,
  NavigationRailThemeProps,
  OutlinedButtonProps,
  OutlinedButtonThemeProps,
  PaginatedDataTableProps,
  PopupMenuDividerProps,
  PopupMenuItemProps,
  CheckedPopupMenuItemProps,
  PopupMenuButtonProps,
  PopupMenuThemeProps,
  LinearProgressIndicatorProps,
  CircularProgressIndicatorProps,
  RefreshProgressIndicatorProps,
  ProgressIndicatorThemeProps,
  RadioProps,
  RadioListTileProps,
  RadioThemeProps,
  RangeSliderProps,
  RefreshIndicatorProps,
  ReorderableListViewProps,
  ScaffoldMessengerProps,
  ScaffoldProps,
  ScrollbarProps,
  ScrollbarThemeProps,
  SearchAnchorProps,
  SearchBarProps,
  SearchBarThemeProps,
  SearchViewThemeProps,
  SegmentedButtonProps,
  SegmentedButtonThemeProps,
  SelectableTextProps,
  SelectionAreaProps,
  SliderProps,
  SliderThemeProps,
  SnackBarActionProps,
  SnackBarProps,
  SnackBarThemeProps,
  SpellCheckSuggestionsToolbarProps,
  StepperProps,
  SwitchProps,
  SwitchListTileProps,
  SwitchThemeProps,
  TabBarThemeProps,
  DefaultTabControllerProps,
  TabProps,
  TabBarProps,
  TabBarViewProps,
  TabPageSelectorIndicatorProps,
  TabPageSelectorProps,
  TextButtonProps,
  TextButtonThemeProps,
  TextFieldProps,
  TextFormFieldProps,
  TextSelectionThemeProps,
  TextSelectionToolbarProps,
  TextSelectionToolbarTextButtonProps,
  ThemeProps,
  AnimatedThemeProps,
  TimePickerDialogProps,
  TimePickerThemeProps,
  ToggleButtonsProps,
  ToggleButtonsThemeProps,
  TooltipProps,
  TooltipThemeProps,
  TooltipVisibilityProps,
  UserAccountsDrawerHeaderProps,
  ActionListenerProps,
  ActionsProps,
  FocusableActionDetectorProps,
  RenderObjectToWidgetAdapterProps,
  AnimatedCrossFadeProps,
  AnimatedListProps,
  AnimatedGridProps,
  SliverAnimatedListProps,
  SliverAnimatedGridProps,
  AnimatedSizeProps,
  AnimatedSwitcherProps,
  AnnotatedRegionProps,
  WidgetsAppProps,
  StreamBuilderProps,
  FutureBuilderProps,
  RawAutocompleteProps,
  AutocompleteHighlightedOptionProps,
  AutofillGroupProps,
  AutomaticKeepAliveProps,
  BannerProps,
  CheckedModeBannerProps,
  DirectionalityProps,
  OpacityProps,
  ShaderMaskProps,
  BackdropGroupProps,
  BackdropFilterProps,
  CustomPaintProps,
  ClipRectProps,
  ClipRRectProps,
  ClipRSuperellipseProps,
  ClipOvalProps,
  ClipPathProps,
  PhysicalModelProps,
  PhysicalShapeProps,
  TransformProps,
  CompositedTransformTargetProps,
  CompositedTransformFollowerProps,
  FittedBoxProps,
  FractionalTranslationProps,
  RotatedBoxProps,
  PaddingProps,
  AlignProps,
  CenterProps,
  CustomSingleChildLayoutProps,
  LayoutIdProps,
  CustomMultiChildLayoutProps,
  SizedBoxProps,
  ConstrainedBoxProps,
  ConstraintsTransformBoxProps,
  UnconstrainedBoxProps,
  FractionallySizedBoxProps,
  LimitedBoxProps,
  OverflowBoxProps,
  SizedOverflowBoxProps,
  OffstageProps,
  AspectRatioProps,
  IntrinsicWidthProps,
  IntrinsicHeightProps,
  BaselineProps,
  IgnoreBaselineProps,
  SliverToBoxAdapterProps,
  SliverPaddingProps,
  SliverSemanticsProps,
  ListBodyProps,
  StackProps,
  IndexedStackProps,
  PositionedProps,
  PositionedDirectionalProps,
  FlexProps,
  RowProps,
  ColumnProps,
  FlexibleProps,
  ExpandedProps,
  WrapProps,
  FlowProps,
  RichTextProps,
  RawImageProps,
  DefaultAssetBundleProps,
  WidgetToRenderBoxAdapterProps,
  ListenerProps,
  MouseRegionProps,
  RepaintBoundaryProps,
  IgnorePointerProps,
  AbsorbPointerProps,
  MetaDataProps,
  SemanticsProps,
  MergeSemanticsProps,
  BlockSemanticsProps,
  ExcludeSemanticsProps,
  IndexedSemanticsProps,
  KeyedSubtreeProps,
  BuilderProps,
  StatefulBuilderProps,
  ColoredBoxProps,
  RootWidgetProps,
  ColorFilteredProps,
  DecoratedBoxProps,
  ContainerProps,
  DecoratedSliverProps,
  DefaultSelectionStyleProps,
  DefaultTextEditingShortcutsProps,
  DismissibleProps,
  DisplayFeatureSubScreenProps,
  DragBoundaryProps,
  DraggableProps,
  LongPressDraggableProps,
  DragTargetProps,
  DraggableScrollableSheetProps,
  DraggableScrollableActuatorProps,
  DualTransitionBuilderProps,
  EditableTextProps,
  ExpansibleProps,
  FadeInImageProps,
  FlutterLogoProps,
  FocusProps,
  FocusScopeProps,
  ExcludeFocusProps,
  FocusTraversalOrderProps,
  FocusTraversalGroupProps,
  ExcludeFocusTraversalProps,
  FormProps,
  FormFieldProps,
  ErrorWidgetProps,
  GestureDetectorProps,
  RawGestureDetectorProps,
  GridPaperProps,
  HeroProps,
  HeroModeProps,
  IconProps,
  IconThemeProps,
  ImageProps,
  ImageFilteredProps,
  ImageIconProps,
  AnimatedContainerProps,
  AnimatedPaddingProps,
  AnimatedAlignProps,
  AnimatedPositionedProps,
  AnimatedPositionedDirectionalProps,
  AnimatedScaleProps,
  AnimatedRotationProps,
  AnimatedSlideProps,
  AnimatedOpacityProps,
  SliverAnimatedOpacityProps,
  AnimatedDefaultTextStyleProps,
  AnimatedPhysicalModelProps,
  AnimatedFractionallySizedBoxProps,
  InteractiveViewerProps,
  KeyboardListenerProps,
  LayoutBuilderProps,
  ListWheelScrollViewProps,
  ListWheelViewportProps,
  LocalizationsProps,
  LookupBoundaryProps,
  RawMagnifierProps,
  MediaQueryProps,
  ModalBarrierProps,
  AnimatedModalBarrierProps,
  NavigationToolbarProps,
  HeroControllerScopeProps,
  NavigatorProps,
  NavigatorPopHandlerProps,
  NestedScrollViewProps,
  SliverOverlapAbsorberProps,
  SliverOverlapInjectorProps,
  NestedScrollViewViewportProps,
  NotificationListenerProps,
  OrientationBuilderProps,
  DeviceOrientationBuilderProps,
  OverflowBarProps,
  OverlayProps,
  OverlayPortalProps,
  GlowingOverscrollIndicatorProps,
  StretchingOverscrollIndicatorProps,
  PageStorageProps,
  PageViewProps,
  PerformanceOverlayProps,
  PinnedHeaderSliverProps,
  PlaceholderProps,
  PlatformMenuBarProps,
  PlatformSelectableRegionContextMenuProps,
  AndroidViewProps,
  UiKitViewProps,
  AppKitViewProps,
  HtmlElementViewProps,
  PlatformViewLinkProps,
  PlatformViewSurfaceProps,
  AndroidViewSurfaceProps,
  PopScopeProps,
  PreferredSizeProps,
  PrimaryScrollControllerProps,
  RadioGroupProps,
  RawKeyboardListenerProps,
  RawMenuAnchorProps,
  RawMenuAnchorGroupProps,
  RawRadioProps,
  RawTooltipProps,
  ReorderableListProps,
  SliverReorderableListProps,
  ReorderableDragStartListenerProps,
  ReorderableDelayedDragStartListenerProps,
  RepeatingAnimationBuilderProps,
  RestorationScopeProps,
  UnmanagedRestorationScopeProps,
  RootRestorationScopeProps,
  RouterProps,
  BackButtonListenerProps,
  SafeAreaProps,
  SliverSafeAreaProps,
  ScrollConfigurationProps,
  ScrollNotificationObserverProps,
  CustomScrollViewProps,
  ListViewProps,
  GridViewProps,
  ScrollableProps,
  TwoDimensionalScrollableProps,
  RawScrollbarProps,
  SelectableRegionProps,
  SelectableRegionSelectionStatusScopeProps,
  SelectionListenerProps,
  SelectionContainerProps,
  SelectionRegistrarScopeProps,
  SemanticsDebuggerProps,
  SensitiveContentProps,
  SharedAppDataProps,
  ShortcutsProps,
  CallbackShortcutsProps,
  ShortcutRegistrarProps,
  SingleChildScrollViewProps,
  SizeChangedLayoutNotifierProps,
  SliverListProps,
  SliverFixedExtentListProps,
  SliverVariedExtentListProps,
  SliverGridProps,
  SliverOpacityProps,
  SliverIgnorePointerProps,
  SliverOffstageProps,
  KeepAliveProps,
  SliverConstrainedCrossAxisProps,
  SliverCrossAxisExpandedProps,
  SliverCrossAxisGroupProps,
  SliverMainAxisGroupProps,
  SliverEnsureSemanticsProps,
  SliverFillViewportProps,
  SliverFillRemainingProps,
  SliverFloatingHeaderProps,
  SliverLayoutBuilderProps,
  SliverPersistentHeaderProps,
  SliverPrototypeExtentListProps,
  SliverResizingHeaderProps,
  TreeSliverProps,
  SnapshotWidgetProps,
  SpacerProps,
  StretchEffectProps,
  SystemContextMenuProps,
  TableProps,
  TableCellProps,
  TapRegionSurfaceProps,
  TapRegionProps,
  TextFieldTapRegionProps,
  DefaultTextStyleProps,
  DefaultTextHeightBehaviorProps,
  TextProps,
  TextSelectionGestureDetectorProps,
  TextureProps,
  TickerModeProps,
  TitleProps,
  SlideTransitionProps,
  MatrixTransitionProps,
  ScaleTransitionProps,
  RotationTransitionProps,
  SizeTransitionProps,
  FadeTransitionProps,
  SliverFadeTransitionProps,
  PositionedTransitionProps,
  RelativePositionedTransitionProps,
  DecoratedBoxTransitionProps,
  AlignTransitionProps,
  DefaultTextStyleTransitionProps,
  ListenableBuilderProps,
  AnimatedBuilderProps,
  TweenAnimationBuilderProps,
  UndoHistoryProps,
  ValueListenableBuilderProps,
  ViewProps,
  RawViewProps,
  ViewCollectionProps,
  ViewAnchorProps,
  ViewportProps,
  ShrinkWrappingViewportProps,
  VisibilityProps,
  SliverVisibilityProps,
  WidgetInspectorProps,
  EnableWidgetInspectorScopeProps,
  DisableWidgetInspectorScopeProps,
  WillPopScopeProps,
  CupertinoActivityIndicatorProps,
  CupertinoLinearActivityIndicatorProps,
  CupertinoAdaptiveTextSelectionToolbarProps,
  CupertinoAppProps,
  CupertinoTabBarProps,
  CupertinoButtonProps,
  CupertinoCheckboxProps,
  CupertinoContextMenuProps,
  CupertinoContextMenuActionProps,
  CupertinoFocusHaloProps,
  CupertinoDatePickerProps,
  CupertinoTimerPickerProps,
  CupertinoDesktopTextSelectionToolbarProps,
  CupertinoDesktopTextSelectionToolbarButtonProps,
  CupertinoAlertDialogProps,
  CupertinoPopupSurfaceProps,
  CupertinoActionSheetProps,
  CupertinoActionSheetActionProps,
  CupertinoDialogActionProps,
  CupertinoExpansionTileProps,
  CupertinoFormRowProps,
  CupertinoFormSectionProps,
  CupertinoUserInterfaceLevelProps,
  CupertinoListSectionProps,
  CupertinoListTileProps,
  CupertinoListTileChevronProps,
  CupertinoTextMagnifierProps,
  CupertinoMagnifierProps,
  CupertinoNavigationBarProps,
  CupertinoSliverNavigationBarProps,
  CupertinoNavigationBarBackButtonProps,
  CupertinoPageScaffoldProps,
  CupertinoPageScaffoldBackgroundColorProps,
  CupertinoPickerProps,
  CupertinoPickerDefaultSelectionOverlayProps,
  CupertinoRadioProps,
  CupertinoSliverRefreshControlProps,
  CupertinoPageTransitionProps,
  CupertinoFullscreenDialogTransitionProps,
  CupertinoScrollbarProps,
  CupertinoSearchTextFieldProps,
  CupertinoSegmentedControlProps,
  CupertinoSheetTransitionProps,
  CupertinoSliderProps,
  CupertinoSlidingSegmentedControlProps,
  CupertinoSpellCheckSuggestionsToolbarProps,
  CupertinoSwitchProps,
  CupertinoTabScaffoldProps,
  CupertinoTabViewProps,
  CupertinoTextFieldProps,
  CupertinoTextFormFieldRowProps,
  CupertinoTextSelectionToolbarProps,
  CupertinoTextSelectionToolbarButtonProps,
  CupertinoThemeProps,
  InheritedCupertinoThemeProps
} from '../src/generated/widget-interfaces.js';

declare global {
  namespace JSX {
    interface Element extends import('../src/core/widget-node.js').WidgetNode {}
    interface IntrinsicElements {
      AboutListTile: AboutListTileProps;
      AboutDialog: AboutDialogProps;
      LicensePage: LicensePageProps;
      BackButtonIcon: BackButtonIconProps;
      BackButton: BackButtonProps;
      CloseButtonIcon: CloseButtonIconProps;
      CloseButton: CloseButtonProps;
      DrawerButtonIcon: DrawerButtonIconProps;
      DrawerButton: DrawerButtonProps;
      EndDrawerButtonIcon: EndDrawerButtonIconProps;
      EndDrawerButton: EndDrawerButtonProps;
      ActionChip: ActionChipProps;
      ActionIconTheme: ActionIconThemeProps;
      AdaptiveTextSelectionToolbar: AdaptiveTextSelectionToolbarProps;
      AnimatedIcon: AnimatedIconProps;
      MaterialApp: MaterialAppProps;
      AppBar: AppBarProps;
      SliverAppBar: SliverAppBarProps;
      AppBarTheme: AppBarThemeProps;
      Autocomplete: AutocompleteProps;
      Badge: BadgeProps;
      BadgeTheme: BadgeThemeProps;
      MaterialBanner: MaterialBannerProps;
      MaterialBannerTheme: MaterialBannerThemeProps;
      BottomAppBar: BottomAppBarProps;
      BottomAppBarTheme: BottomAppBarThemeProps;
      BottomNavigationBar: BottomNavigationBarProps;
      BottomNavigationBarTheme: BottomNavigationBarThemeProps;
      BottomSheet: BottomSheetProps;
      RawMaterialButton: RawMaterialButtonProps;
      ButtonBar: ButtonBarProps;
      ButtonBarTheme: ButtonBarThemeProps;
      ButtonTheme: ButtonThemeProps;
      CalendarDatePicker: CalendarDatePickerProps;
      YearPicker: YearPickerProps;
      Card: CardProps;
      CardTheme: CardThemeProps;
      CarouselView: CarouselViewProps;
      CarouselViewTheme: CarouselViewThemeProps;
      Checkbox: CheckboxProps;
      CheckboxListTile: CheckboxListTileProps;
      CheckboxTheme: CheckboxThemeProps;
      Chip: ChipProps;
      RawChip: RawChipProps;
      ChipTheme: ChipThemeProps;
      ChoiceChip: ChoiceChipProps;
      CircleAvatar: CircleAvatarProps;
      DataTable: DataTableProps;
      TableRowInkWell: TableRowInkWellProps;
      DataTableTheme: DataTableThemeProps;
      DatePickerDialog: DatePickerDialogProps;
      DateRangePickerDialog: DateRangePickerDialogProps;
      DatePickerTheme: DatePickerThemeProps;
      DesktopTextSelectionToolbar: DesktopTextSelectionToolbarProps;
      DesktopTextSelectionToolbarButton: DesktopTextSelectionToolbarButtonProps;
      Dialog: DialogProps;
      AlertDialog: AlertDialogProps;
      SimpleDialogOption: SimpleDialogOptionProps;
      SimpleDialog: SimpleDialogProps;
      DialogTheme: DialogThemeProps;
      Divider: DividerProps;
      VerticalDivider: VerticalDividerProps;
      DividerTheme: DividerThemeProps;
      Drawer: DrawerProps;
      DrawerController: DrawerControllerProps;
      DrawerHeader: DrawerHeaderProps;
      DrawerTheme: DrawerThemeProps;
      DropdownMenuItem: DropdownMenuItemProps;
      DropdownButtonHideUnderline: DropdownButtonHideUnderlineProps;
      DropdownButton: DropdownButtonProps;
      DropdownButtonFormField: DropdownButtonFormFieldProps;
      DropdownMenu: DropdownMenuProps;
      DropdownMenuFormField: DropdownMenuFormFieldProps;
      DropdownMenuTheme: DropdownMenuThemeProps;
      ElevatedButton: ElevatedButtonProps;
      ElevatedButtonTheme: ElevatedButtonThemeProps;
      ExpandIcon: ExpandIconProps;
      ExpansionPanelList: ExpansionPanelListProps;
      ExpansionTile: ExpansionTileProps;
      ExpansionTileTheme: ExpansionTileThemeProps;
      FilledButton: FilledButtonProps;
      FilledButtonTheme: FilledButtonThemeProps;
      FilterChip: FilterChipProps;
      FlexibleSpaceBar: FlexibleSpaceBarProps;
      FlexibleSpaceBarSettings: FlexibleSpaceBarSettingsProps;
      FloatingActionButton: FloatingActionButtonProps;
      FloatingActionButtonTheme: FloatingActionButtonThemeProps;
      GridTile: GridTileProps;
      GridTileBar: GridTileBarProps;
      IconButton: IconButtonProps;
      IconButtonTheme: IconButtonThemeProps;
      Ink: InkProps;
      InkResponse: InkResponseProps;
      InkWell: InkWellProps;
      InputChip: InputChipProps;
      InputDatePickerFormField: InputDatePickerFormFieldProps;
      InputDecorator: InputDecoratorProps;
      InputDecorationTheme: InputDecorationThemeProps;
      ListTile: ListTileProps;
      ListTileTheme: ListTileThemeProps;
      TextMagnifier: TextMagnifierProps;
      Magnifier: MagnifierProps;
      Material: MaterialProps;
      MaterialButton: MaterialButtonProps;
      MenuAnchor: MenuAnchorProps;
      MenuBar: MenuBarProps;
      MenuItemButton: MenuItemButtonProps;
      CheckboxMenuButton: CheckboxMenuButtonProps;
      RadioMenuButton: RadioMenuButtonProps;
      SubmenuButton: SubmenuButtonProps;
      MenuAcceleratorCallbackBinding: MenuAcceleratorCallbackBindingProps;
      MenuAcceleratorLabel: MenuAcceleratorLabelProps;
      MenuBarTheme: MenuBarThemeProps;
      MenuButtonTheme: MenuButtonThemeProps;
      MenuTheme: MenuThemeProps;
      MergeableMaterial: MergeableMaterialProps;
      NavigationBar: NavigationBarProps;
      NavigationDestination: NavigationDestinationProps;
      NavigationIndicator: NavigationIndicatorProps;
      NavigationBarTheme: NavigationBarThemeProps;
      NavigationDrawer: NavigationDrawerProps;
      NavigationDrawerDestination: NavigationDrawerDestinationProps;
      NavigationDrawerTheme: NavigationDrawerThemeProps;
      NavigationRail: NavigationRailProps;
      NavigationRailTheme: NavigationRailThemeProps;
      OutlinedButton: OutlinedButtonProps;
      OutlinedButtonTheme: OutlinedButtonThemeProps;
      PaginatedDataTable: PaginatedDataTableProps;
      PopupMenuDivider: PopupMenuDividerProps;
      PopupMenuItem: PopupMenuItemProps;
      CheckedPopupMenuItem: CheckedPopupMenuItemProps;
      PopupMenuButton: PopupMenuButtonProps;
      PopupMenuTheme: PopupMenuThemeProps;
      LinearProgressIndicator: LinearProgressIndicatorProps;
      CircularProgressIndicator: CircularProgressIndicatorProps;
      RefreshProgressIndicator: RefreshProgressIndicatorProps;
      ProgressIndicatorTheme: ProgressIndicatorThemeProps;
      Radio: RadioProps;
      RadioListTile: RadioListTileProps;
      RadioTheme: RadioThemeProps;
      RangeSlider: RangeSliderProps;
      RefreshIndicator: RefreshIndicatorProps;
      ReorderableListView: ReorderableListViewProps;
      ScaffoldMessenger: ScaffoldMessengerProps;
      Scaffold: ScaffoldProps;
      Scrollbar: ScrollbarProps;
      ScrollbarTheme: ScrollbarThemeProps;
      SearchAnchor: SearchAnchorProps;
      SearchBar: SearchBarProps;
      SearchBarTheme: SearchBarThemeProps;
      SearchViewTheme: SearchViewThemeProps;
      SegmentedButton: SegmentedButtonProps;
      SegmentedButtonTheme: SegmentedButtonThemeProps;
      SelectableText: SelectableTextProps;
      SelectionArea: SelectionAreaProps;
      Slider: SliderProps;
      SliderTheme: SliderThemeProps;
      SnackBarAction: SnackBarActionProps;
      SnackBar: SnackBarProps;
      SnackBarTheme: SnackBarThemeProps;
      SpellCheckSuggestionsToolbar: SpellCheckSuggestionsToolbarProps;
      Stepper: StepperProps;
      Switch: SwitchProps;
      SwitchListTile: SwitchListTileProps;
      SwitchTheme: SwitchThemeProps;
      TabBarTheme: TabBarThemeProps;
      DefaultTabController: DefaultTabControllerProps;
      Tab: TabProps;
      TabBar: TabBarProps;
      TabBarView: TabBarViewProps;
      TabPageSelectorIndicator: TabPageSelectorIndicatorProps;
      TabPageSelector: TabPageSelectorProps;
      TextButton: TextButtonProps;
      TextButtonTheme: TextButtonThemeProps;
      TextField: TextFieldProps;
      TextFormField: TextFormFieldProps;
      TextSelectionTheme: TextSelectionThemeProps;
      TextSelectionToolbar: TextSelectionToolbarProps;
      TextSelectionToolbarTextButton: TextSelectionToolbarTextButtonProps;
      Theme: ThemeProps;
      AnimatedTheme: AnimatedThemeProps;
      TimePickerDialog: TimePickerDialogProps;
      TimePickerTheme: TimePickerThemeProps;
      ToggleButtons: ToggleButtonsProps;
      ToggleButtonsTheme: ToggleButtonsThemeProps;
      Tooltip: TooltipProps;
      TooltipTheme: TooltipThemeProps;
      TooltipVisibility: TooltipVisibilityProps;
      UserAccountsDrawerHeader: UserAccountsDrawerHeaderProps;
      ActionListener: ActionListenerProps;
      Actions: ActionsProps;
      FocusableActionDetector: FocusableActionDetectorProps;
      RenderObjectToWidgetAdapter: RenderObjectToWidgetAdapterProps;
      AnimatedCrossFade: AnimatedCrossFadeProps;
      AnimatedList: AnimatedListProps;
      AnimatedGrid: AnimatedGridProps;
      SliverAnimatedList: SliverAnimatedListProps;
      SliverAnimatedGrid: SliverAnimatedGridProps;
      AnimatedSize: AnimatedSizeProps;
      AnimatedSwitcher: AnimatedSwitcherProps;
      AnnotatedRegion: AnnotatedRegionProps;
      WidgetsApp: WidgetsAppProps;
      StreamBuilder: StreamBuilderProps;
      FutureBuilder: FutureBuilderProps;
      RawAutocomplete: RawAutocompleteProps;
      AutocompleteHighlightedOption: AutocompleteHighlightedOptionProps;
      AutofillGroup: AutofillGroupProps;
      AutomaticKeepAlive: AutomaticKeepAliveProps;
      Banner: BannerProps;
      CheckedModeBanner: CheckedModeBannerProps;
      Directionality: DirectionalityProps;
      Opacity: OpacityProps;
      ShaderMask: ShaderMaskProps;
      BackdropGroup: BackdropGroupProps;
      BackdropFilter: BackdropFilterProps;
      CustomPaint: CustomPaintProps;
      ClipRect: ClipRectProps;
      ClipRRect: ClipRRectProps;
      ClipRSuperellipse: ClipRSuperellipseProps;
      ClipOval: ClipOvalProps;
      ClipPath: ClipPathProps;
      PhysicalModel: PhysicalModelProps;
      PhysicalShape: PhysicalShapeProps;
      Transform: TransformProps;
      CompositedTransformTarget: CompositedTransformTargetProps;
      CompositedTransformFollower: CompositedTransformFollowerProps;
      FittedBox: FittedBoxProps;
      FractionalTranslation: FractionalTranslationProps;
      RotatedBox: RotatedBoxProps;
      Padding: PaddingProps;
      Align: AlignProps;
      Center: CenterProps;
      CustomSingleChildLayout: CustomSingleChildLayoutProps;
      LayoutId: LayoutIdProps;
      CustomMultiChildLayout: CustomMultiChildLayoutProps;
      SizedBox: SizedBoxProps;
      ConstrainedBox: ConstrainedBoxProps;
      ConstraintsTransformBox: ConstraintsTransformBoxProps;
      UnconstrainedBox: UnconstrainedBoxProps;
      FractionallySizedBox: FractionallySizedBoxProps;
      LimitedBox: LimitedBoxProps;
      OverflowBox: OverflowBoxProps;
      SizedOverflowBox: SizedOverflowBoxProps;
      Offstage: OffstageProps;
      AspectRatio: AspectRatioProps;
      IntrinsicWidth: IntrinsicWidthProps;
      IntrinsicHeight: IntrinsicHeightProps;
      Baseline: BaselineProps;
      IgnoreBaseline: IgnoreBaselineProps;
      SliverToBoxAdapter: SliverToBoxAdapterProps;
      SliverPadding: SliverPaddingProps;
      SliverSemantics: SliverSemanticsProps;
      ListBody: ListBodyProps;
      Stack: StackProps;
      IndexedStack: IndexedStackProps;
      Positioned: PositionedProps;
      PositionedDirectional: PositionedDirectionalProps;
      Flex: FlexProps;
      Row: RowProps;
      Column: ColumnProps;
      Flexible: FlexibleProps;
      Expanded: ExpandedProps;
      Wrap: WrapProps;
      Flow: FlowProps;
      RichText: RichTextProps;
      RawImage: RawImageProps;
      DefaultAssetBundle: DefaultAssetBundleProps;
      WidgetToRenderBoxAdapter: WidgetToRenderBoxAdapterProps;
      Listener: ListenerProps;
      MouseRegion: MouseRegionProps;
      RepaintBoundary: RepaintBoundaryProps;
      IgnorePointer: IgnorePointerProps;
      AbsorbPointer: AbsorbPointerProps;
      MetaData: MetaDataProps;
      Semantics: SemanticsProps;
      MergeSemantics: MergeSemanticsProps;
      BlockSemantics: BlockSemanticsProps;
      ExcludeSemantics: ExcludeSemanticsProps;
      IndexedSemantics: IndexedSemanticsProps;
      KeyedSubtree: KeyedSubtreeProps;
      Builder: BuilderProps;
      StatefulBuilder: StatefulBuilderProps;
      ColoredBox: ColoredBoxProps;
      RootWidget: RootWidgetProps;
      ColorFiltered: ColorFilteredProps;
      DecoratedBox: DecoratedBoxProps;
      Container: ContainerProps;
      DecoratedSliver: DecoratedSliverProps;
      DefaultSelectionStyle: DefaultSelectionStyleProps;
      DefaultTextEditingShortcuts: DefaultTextEditingShortcutsProps;
      Dismissible: DismissibleProps;
      DisplayFeatureSubScreen: DisplayFeatureSubScreenProps;
      DragBoundary: DragBoundaryProps;
      Draggable: DraggableProps;
      LongPressDraggable: LongPressDraggableProps;
      DragTarget: DragTargetProps;
      DraggableScrollableSheet: DraggableScrollableSheetProps;
      DraggableScrollableActuator: DraggableScrollableActuatorProps;
      DualTransitionBuilder: DualTransitionBuilderProps;
      EditableText: EditableTextProps;
      Expansible: ExpansibleProps;
      FadeInImage: FadeInImageProps;
      FlutterLogo: FlutterLogoProps;
      Focus: FocusProps;
      FocusScope: FocusScopeProps;
      ExcludeFocus: ExcludeFocusProps;
      FocusTraversalOrder: FocusTraversalOrderProps;
      FocusTraversalGroup: FocusTraversalGroupProps;
      ExcludeFocusTraversal: ExcludeFocusTraversalProps;
      Form: FormProps;
      FormField: FormFieldProps;
      ErrorWidget: ErrorWidgetProps;
      GestureDetector: GestureDetectorProps;
      RawGestureDetector: RawGestureDetectorProps;
      GridPaper: GridPaperProps;
      Hero: HeroProps;
      HeroMode: HeroModeProps;
      Icon: IconProps;
      IconTheme: IconThemeProps;
      Image: ImageProps;
      ImageFiltered: ImageFilteredProps;
      ImageIcon: ImageIconProps;
      AnimatedContainer: AnimatedContainerProps;
      AnimatedPadding: AnimatedPaddingProps;
      AnimatedAlign: AnimatedAlignProps;
      AnimatedPositioned: AnimatedPositionedProps;
      AnimatedPositionedDirectional: AnimatedPositionedDirectionalProps;
      AnimatedScale: AnimatedScaleProps;
      AnimatedRotation: AnimatedRotationProps;
      AnimatedSlide: AnimatedSlideProps;
      AnimatedOpacity: AnimatedOpacityProps;
      SliverAnimatedOpacity: SliverAnimatedOpacityProps;
      AnimatedDefaultTextStyle: AnimatedDefaultTextStyleProps;
      AnimatedPhysicalModel: AnimatedPhysicalModelProps;
      AnimatedFractionallySizedBox: AnimatedFractionallySizedBoxProps;
      InteractiveViewer: InteractiveViewerProps;
      KeyboardListener: KeyboardListenerProps;
      LayoutBuilder: LayoutBuilderProps;
      ListWheelScrollView: ListWheelScrollViewProps;
      ListWheelViewport: ListWheelViewportProps;
      Localizations: LocalizationsProps;
      LookupBoundary: LookupBoundaryProps;
      RawMagnifier: RawMagnifierProps;
      MediaQuery: MediaQueryProps;
      ModalBarrier: ModalBarrierProps;
      AnimatedModalBarrier: AnimatedModalBarrierProps;
      NavigationToolbar: NavigationToolbarProps;
      HeroControllerScope: HeroControllerScopeProps;
      Navigator: NavigatorProps;
      NavigatorPopHandler: NavigatorPopHandlerProps;
      NestedScrollView: NestedScrollViewProps;
      SliverOverlapAbsorber: SliverOverlapAbsorberProps;
      SliverOverlapInjector: SliverOverlapInjectorProps;
      NestedScrollViewViewport: NestedScrollViewViewportProps;
      NotificationListener: NotificationListenerProps;
      OrientationBuilder: OrientationBuilderProps;
      DeviceOrientationBuilder: DeviceOrientationBuilderProps;
      OverflowBar: OverflowBarProps;
      Overlay: OverlayProps;
      OverlayPortal: OverlayPortalProps;
      GlowingOverscrollIndicator: GlowingOverscrollIndicatorProps;
      StretchingOverscrollIndicator: StretchingOverscrollIndicatorProps;
      PageStorage: PageStorageProps;
      PageView: PageViewProps;
      PerformanceOverlay: PerformanceOverlayProps;
      PinnedHeaderSliver: PinnedHeaderSliverProps;
      Placeholder: PlaceholderProps;
      PlatformMenuBar: PlatformMenuBarProps;
      PlatformSelectableRegionContextMenu: PlatformSelectableRegionContextMenuProps;
      AndroidView: AndroidViewProps;
      UiKitView: UiKitViewProps;
      AppKitView: AppKitViewProps;
      HtmlElementView: HtmlElementViewProps;
      PlatformViewLink: PlatformViewLinkProps;
      PlatformViewSurface: PlatformViewSurfaceProps;
      AndroidViewSurface: AndroidViewSurfaceProps;
      PopScope: PopScopeProps;
      PreferredSize: PreferredSizeProps;
      PrimaryScrollController: PrimaryScrollControllerProps;
      RadioGroup: RadioGroupProps;
      RawKeyboardListener: RawKeyboardListenerProps;
      RawMenuAnchor: RawMenuAnchorProps;
      RawMenuAnchorGroup: RawMenuAnchorGroupProps;
      RawRadio: RawRadioProps;
      RawTooltip: RawTooltipProps;
      ReorderableList: ReorderableListProps;
      SliverReorderableList: SliverReorderableListProps;
      ReorderableDragStartListener: ReorderableDragStartListenerProps;
      ReorderableDelayedDragStartListener: ReorderableDelayedDragStartListenerProps;
      RepeatingAnimationBuilder: RepeatingAnimationBuilderProps;
      RestorationScope: RestorationScopeProps;
      UnmanagedRestorationScope: UnmanagedRestorationScopeProps;
      RootRestorationScope: RootRestorationScopeProps;
      Router: RouterProps;
      BackButtonListener: BackButtonListenerProps;
      SafeArea: SafeAreaProps;
      SliverSafeArea: SliverSafeAreaProps;
      ScrollConfiguration: ScrollConfigurationProps;
      ScrollNotificationObserver: ScrollNotificationObserverProps;
      CustomScrollView: CustomScrollViewProps;
      ListView: ListViewProps;
      GridView: GridViewProps;
      Scrollable: ScrollableProps;
      TwoDimensionalScrollable: TwoDimensionalScrollableProps;
      RawScrollbar: RawScrollbarProps;
      SelectableRegion: SelectableRegionProps;
      SelectableRegionSelectionStatusScope: SelectableRegionSelectionStatusScopeProps;
      SelectionListener: SelectionListenerProps;
      SelectionContainer: SelectionContainerProps;
      SelectionRegistrarScope: SelectionRegistrarScopeProps;
      SemanticsDebugger: SemanticsDebuggerProps;
      SensitiveContent: SensitiveContentProps;
      SharedAppData: SharedAppDataProps;
      Shortcuts: ShortcutsProps;
      CallbackShortcuts: CallbackShortcutsProps;
      ShortcutRegistrar: ShortcutRegistrarProps;
      SingleChildScrollView: SingleChildScrollViewProps;
      SizeChangedLayoutNotifier: SizeChangedLayoutNotifierProps;
      SliverList: SliverListProps;
      SliverFixedExtentList: SliverFixedExtentListProps;
      SliverVariedExtentList: SliverVariedExtentListProps;
      SliverGrid: SliverGridProps;
      SliverOpacity: SliverOpacityProps;
      SliverIgnorePointer: SliverIgnorePointerProps;
      SliverOffstage: SliverOffstageProps;
      KeepAlive: KeepAliveProps;
      SliverConstrainedCrossAxis: SliverConstrainedCrossAxisProps;
      SliverCrossAxisExpanded: SliverCrossAxisExpandedProps;
      SliverCrossAxisGroup: SliverCrossAxisGroupProps;
      SliverMainAxisGroup: SliverMainAxisGroupProps;
      SliverEnsureSemantics: SliverEnsureSemanticsProps;
      SliverFillViewport: SliverFillViewportProps;
      SliverFillRemaining: SliverFillRemainingProps;
      SliverFloatingHeader: SliverFloatingHeaderProps;
      SliverLayoutBuilder: SliverLayoutBuilderProps;
      SliverPersistentHeader: SliverPersistentHeaderProps;
      SliverPrototypeExtentList: SliverPrototypeExtentListProps;
      SliverResizingHeader: SliverResizingHeaderProps;
      TreeSliver: TreeSliverProps;
      SnapshotWidget: SnapshotWidgetProps;
      Spacer: SpacerProps;
      StretchEffect: StretchEffectProps;
      SystemContextMenu: SystemContextMenuProps;
      Table: TableProps;
      TableCell: TableCellProps;
      TapRegionSurface: TapRegionSurfaceProps;
      TapRegion: TapRegionProps;
      TextFieldTapRegion: TextFieldTapRegionProps;
      DefaultTextStyle: DefaultTextStyleProps;
      DefaultTextHeightBehavior: DefaultTextHeightBehaviorProps;
      Text: TextProps;
      TextSelectionGestureDetector: TextSelectionGestureDetectorProps;
      Texture: TextureProps;
      TickerMode: TickerModeProps;
      Title: TitleProps;
      SlideTransition: SlideTransitionProps;
      MatrixTransition: MatrixTransitionProps;
      ScaleTransition: ScaleTransitionProps;
      RotationTransition: RotationTransitionProps;
      SizeTransition: SizeTransitionProps;
      FadeTransition: FadeTransitionProps;
      SliverFadeTransition: SliverFadeTransitionProps;
      PositionedTransition: PositionedTransitionProps;
      RelativePositionedTransition: RelativePositionedTransitionProps;
      DecoratedBoxTransition: DecoratedBoxTransitionProps;
      AlignTransition: AlignTransitionProps;
      DefaultTextStyleTransition: DefaultTextStyleTransitionProps;
      ListenableBuilder: ListenableBuilderProps;
      AnimatedBuilder: AnimatedBuilderProps;
      TweenAnimationBuilder: TweenAnimationBuilderProps;
      UndoHistory: UndoHistoryProps;
      ValueListenableBuilder: ValueListenableBuilderProps;
      View: ViewProps;
      RawView: RawViewProps;
      ViewCollection: ViewCollectionProps;
      ViewAnchor: ViewAnchorProps;
      Viewport: ViewportProps;
      ShrinkWrappingViewport: ShrinkWrappingViewportProps;
      Visibility: VisibilityProps;
      SliverVisibility: SliverVisibilityProps;
      WidgetInspector: WidgetInspectorProps;
      EnableWidgetInspectorScope: EnableWidgetInspectorScopeProps;
      DisableWidgetInspectorScope: DisableWidgetInspectorScopeProps;
      WillPopScope: WillPopScopeProps;
      CupertinoActivityIndicator: CupertinoActivityIndicatorProps;
      CupertinoLinearActivityIndicator: CupertinoLinearActivityIndicatorProps;
      CupertinoAdaptiveTextSelectionToolbar: CupertinoAdaptiveTextSelectionToolbarProps;
      CupertinoApp: CupertinoAppProps;
      CupertinoTabBar: CupertinoTabBarProps;
      CupertinoButton: CupertinoButtonProps;
      CupertinoCheckbox: CupertinoCheckboxProps;
      CupertinoContextMenu: CupertinoContextMenuProps;
      CupertinoContextMenuAction: CupertinoContextMenuActionProps;
      CupertinoFocusHalo: CupertinoFocusHaloProps;
      CupertinoDatePicker: CupertinoDatePickerProps;
      CupertinoTimerPicker: CupertinoTimerPickerProps;
      CupertinoDesktopTextSelectionToolbar: CupertinoDesktopTextSelectionToolbarProps;
      CupertinoDesktopTextSelectionToolbarButton: CupertinoDesktopTextSelectionToolbarButtonProps;
      CupertinoAlertDialog: CupertinoAlertDialogProps;
      CupertinoPopupSurface: CupertinoPopupSurfaceProps;
      CupertinoActionSheet: CupertinoActionSheetProps;
      CupertinoActionSheetAction: CupertinoActionSheetActionProps;
      CupertinoDialogAction: CupertinoDialogActionProps;
      CupertinoExpansionTile: CupertinoExpansionTileProps;
      CupertinoFormRow: CupertinoFormRowProps;
      CupertinoFormSection: CupertinoFormSectionProps;
      CupertinoUserInterfaceLevel: CupertinoUserInterfaceLevelProps;
      CupertinoListSection: CupertinoListSectionProps;
      CupertinoListTile: CupertinoListTileProps;
      CupertinoListTileChevron: CupertinoListTileChevronProps;
      CupertinoTextMagnifier: CupertinoTextMagnifierProps;
      CupertinoMagnifier: CupertinoMagnifierProps;
      CupertinoNavigationBar: CupertinoNavigationBarProps;
      CupertinoSliverNavigationBar: CupertinoSliverNavigationBarProps;
      CupertinoNavigationBarBackButton: CupertinoNavigationBarBackButtonProps;
      CupertinoPageScaffold: CupertinoPageScaffoldProps;
      CupertinoPageScaffoldBackgroundColor: CupertinoPageScaffoldBackgroundColorProps;
      CupertinoPicker: CupertinoPickerProps;
      CupertinoPickerDefaultSelectionOverlay: CupertinoPickerDefaultSelectionOverlayProps;
      CupertinoRadio: CupertinoRadioProps;
      CupertinoSliverRefreshControl: CupertinoSliverRefreshControlProps;
      CupertinoPageTransition: CupertinoPageTransitionProps;
      CupertinoFullscreenDialogTransition: CupertinoFullscreenDialogTransitionProps;
      CupertinoScrollbar: CupertinoScrollbarProps;
      CupertinoSearchTextField: CupertinoSearchTextFieldProps;
      CupertinoSegmentedControl: CupertinoSegmentedControlProps;
      CupertinoSheetTransition: CupertinoSheetTransitionProps;
      CupertinoSlider: CupertinoSliderProps;
      CupertinoSlidingSegmentedControl: CupertinoSlidingSegmentedControlProps;
      CupertinoSpellCheckSuggestionsToolbar: CupertinoSpellCheckSuggestionsToolbarProps;
      CupertinoSwitch: CupertinoSwitchProps;
      CupertinoTabScaffold: CupertinoTabScaffoldProps;
      CupertinoTabView: CupertinoTabViewProps;
      CupertinoTextField: CupertinoTextFieldProps;
      CupertinoTextFormFieldRow: CupertinoTextFormFieldRowProps;
      CupertinoTextSelectionToolbar: CupertinoTextSelectionToolbarProps;
      CupertinoTextSelectionToolbarButton: CupertinoTextSelectionToolbarButtonProps;
      CupertinoTheme: CupertinoThemeProps;
      InheritedCupertinoTheme: InheritedCupertinoThemeProps;
    }
  }
}
