// DO NOT EDIT — generated by `fsx define`
import type {
  TextProps,
  ColumnProps,
  RowProps,
  ContainerProps,
  ScaffoldProps,
  MaterialAppProps,
  AppBarProps,
  ElevatedButtonProps,
  TextButtonProps,
  IconButtonProps,
  ImageProps,
  ListViewProps,
  GridViewProps,
  StackProps,
  PaddingProps,
  CenterProps,
  SizedBoxProps,
  DividerProps,
  IconProps,
  TextFieldProps,
  SwitchProps,
  CheckboxProps,
  SliderProps,
  CircularProgressIndicatorProps,
  AlertDialogProps,
  CardProps,
  ListTileProps,
  ExpandedProps,
  FlexibleProps,
  WrapProps,
  FloatingActionButtonProps,
  OutlinedButtonProps,
  AlignProps
} from '../src/generated/widget-interfaces.js';

declare global {
  namespace JSX {
    interface Element extends import('../src/core/widget-node.js').WidgetNode {}
    interface IntrinsicElements {
      Text: TextProps;
      Column: ColumnProps;
      Row: RowProps;
      Container: ContainerProps;
      Scaffold: ScaffoldProps;
      MaterialApp: MaterialAppProps;
      AppBar: AppBarProps;
      ElevatedButton: ElevatedButtonProps;
      TextButton: TextButtonProps;
      IconButton: IconButtonProps;
      Image: ImageProps;
      ListView: ListViewProps;
      GridView: GridViewProps;
      Stack: StackProps;
      Padding: PaddingProps;
      Center: CenterProps;
      SizedBox: SizedBoxProps;
      Divider: DividerProps;
      Icon: IconProps;
      TextField: TextFieldProps;
      Switch: SwitchProps;
      Checkbox: CheckboxProps;
      Slider: SliderProps;
      CircularProgressIndicator: CircularProgressIndicatorProps;
      AlertDialog: AlertDialogProps;
      Card: CardProps;
      ListTile: ListTileProps;
      Expanded: ExpandedProps;
      Flexible: FlexibleProps;
      Wrap: WrapProps;
      FloatingActionButton: FloatingActionButtonProps;
      OutlinedButton: OutlinedButtonProps;
      Align: AlignProps;
    }
  }
}
