// DO NOT EDIT — generated by `fsx define`
import type {
  MaterialAppProps,
  ScaffoldProps,
  CenterProps,
  ContainerProps,
  AppBarProps,
  ColumnProps,
  RowProps,
  ListViewProps,
  GridViewProps,
  StackProps,
  TextProps,
  ElevatedButtonProps,
  TextButtonProps,
  OutlinedButtonProps,
  IconButtonProps,
  CardProps,
  PaddingProps,
  ExpandedProps,
  FlexibleProps,
  AlignProps,
  SizedBoxProps,
  WrapProps,
  ListTileProps,
  BottomNavigationBarProps,
  DrawerProps,
  AlertDialogProps,
  ImageProps,
  IconProps,
  TextFieldProps,
  SwitchProps,
  CheckboxProps,
  SliderProps,
  CircularProgressIndicatorProps,
  LinearProgressIndicatorProps,
  DividerProps,
  SnackBarProps,
  BottomSheetProps,
  NavigationBarProps,
  TabBarProps,
  TabBarViewProps,
  FloatingActionButtonProps
} from '../src/generated/widget-interfaces.js';

declare global {
  namespace JSX {
    interface Element extends import('../src/core/widget-node.js').WidgetNode {}
    interface IntrinsicElements {
      MaterialApp: MaterialAppProps;
      Scaffold: ScaffoldProps;
      Center: CenterProps;
      Container: ContainerProps;
      AppBar: AppBarProps;
      Column: ColumnProps;
      Row: RowProps;
      ListView: ListViewProps;
      GridView: GridViewProps;
      Stack: StackProps;
      Text: TextProps;
      ElevatedButton: ElevatedButtonProps;
      TextButton: TextButtonProps;
      OutlinedButton: OutlinedButtonProps;
      IconButton: IconButtonProps;
      Card: CardProps;
      Padding: PaddingProps;
      Expanded: ExpandedProps;
      Flexible: FlexibleProps;
      Align: AlignProps;
      SizedBox: SizedBoxProps;
      Wrap: WrapProps;
      ListTile: ListTileProps;
      BottomNavigationBar: BottomNavigationBarProps;
      Drawer: DrawerProps;
      AlertDialog: AlertDialogProps;
      Image: ImageProps;
      Icon: IconProps;
      TextField: TextFieldProps;
      Switch: SwitchProps;
      Checkbox: CheckboxProps;
      Slider: SliderProps;
      CircularProgressIndicator: CircularProgressIndicatorProps;
      LinearProgressIndicator: LinearProgressIndicatorProps;
      Divider: DividerProps;
      SnackBar: SnackBarProps;
      BottomSheet: BottomSheetProps;
      NavigationBar: NavigationBarProps;
      TabBar: TabBarProps;
      TabBarView: TabBarViewProps;
      FloatingActionButton: FloatingActionButtonProps;
    }
  }
}
