import '../helpers/resemble.js';

import { describe, expect, it } from 'bun:test';

import type { AppConfig } from '@src/config.js';
import type { DetectedAssets } from '@src/flutter/assets.js';
import type { FontMap } from '@src/flutter/fonts.js';
import { pubspecYaml } from '@src/templates/pubspec-yaml.js';

const baseConfig: AppConfig = {
  name: 'my_app',
};

// ── Full expected pubspec.yaml documents (asserted in their entirety) ──
const BASE = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true`;

const EXTRA_CAMERA = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    camera: ^0.10.6+2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true`;

const MERGE_PROVIDER_CAMERA = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    provider: ^6.0.0
    camera: ^0.10.6+2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true`;

const EXTRA_PROVIDER = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    provider: ^6.0.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true`;

const ASSETS = `${BASE}
    assets:
      - assets/config.json
      - assets/images/`;

const LEGAL_PRIVACY = `${BASE}
    assets:
      - assets/legal/privacy.md`;

const LEGAL_BOTH = `${BASE}
    assets:
      - assets/legal/privacy.md
      - assets/legal/terms.md`;

const FONTS_ONE = `${BASE}
    fonts:
      - family: Inter
        fonts:
          - asset: .fsx-fonts/Inter-Regular.ttf
            weight: 400`;

// Brand-asset variants share this dev_dependencies + header prefix; only the
// trailing flutter_launcher_icons / flutter_native_splash blocks differ.
const BRAND_HEAD = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.14.1
    flutter_native_splash: ^2.4.3

  flutter:
    uses-material-design: true`;

const SPLASH = `
  name: my_app
  description: Generated by flutter.tsx
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'
    flutter: '>=3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0
    flutter_native_splash: ^2.4.3

  flutter:
    uses-material-design: true
  flutter_native_splash:
    image: '.fsx-assets/icons/splash.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON_SPLASH = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
  flutter_native_splash:
    image: '.fsx-assets/icons/splash.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON_BG = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '.fsx-assets/icons/background.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    background_image: '.fsx-assets/icons/background.png'
    android: true
    ios: true
    web: true`;

const ICON_MONO = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
    adaptive_icon_monochrome: '.fsx-assets/icons/monochrome.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON_ICONDARK = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
    image_path_dark: '.fsx-assets/icons/dark/icon.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON_BGDARK = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
    adaptive_icon_background_dark: '.fsx-assets/icons/dark/background.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true
    background_image_dark: '.fsx-assets/icons/dark/background.png'`;

const ICON_MONODARK = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
    adaptive_icon_monochrome_dark: '.fsx-assets/icons/dark/monochrome.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true`;

const ICON_SPLASHDARK = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '#ffffff'
  flutter_native_splash:
    image: '.fsx-assets/icons/icon.png'
    color: '#ffffff'
    android: true
    ios: true
    web: true
    image_dark: '.fsx-assets/icons/dark/splash.png'`;

const ALL8 = `${BRAND_HEAD}
  flutter_launcher_icons:
    image_path: '.fsx-assets/icons/icon.png'
    android: true
    ios: true
    web:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    macos:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    windows:
      generate: true
      image_path: '.fsx-assets/icons/icon.png'
    adaptive_icon_foreground: '.fsx-assets/icons/icon.png'
    adaptive_icon_background: '.fsx-assets/icons/background.png'
    adaptive_icon_monochrome: '.fsx-assets/icons/monochrome.png'
    image_path_dark: '.fsx-assets/icons/dark/icon.png'
    adaptive_icon_background_dark: '.fsx-assets/icons/dark/background.png'
    adaptive_icon_monochrome_dark: '.fsx-assets/icons/dark/monochrome.png'
  flutter_native_splash:
    image: '.fsx-assets/icons/splash.png'
    background_image: '.fsx-assets/icons/background.png'
    android: true
    ios: true
    web: true
    image_dark: '.fsx-assets/icons/dark/splash.png'
    background_image_dark: '.fsx-assets/icons/dark/background.png'`;

describe('pubspecYaml — extraDeps', () => {
  it('includes extraDeps in the output', () => {
    expect(pubspecYaml(baseConfig, ['camera: ^0.10.6+2'])).toResemble(
      EXTRA_CAMERA,
    );
  });

  it('merges extraDeps with config.dependencies', () => {
    const config: AppConfig = {
      ...baseConfig,
      dependencies: { provider: '^6.0.0' },
    };
    expect(pubspecYaml(config, ['camera: ^0.10.6+2'])).toResemble(
      MERGE_PROVIDER_CAMERA,
    );
  });

  it('de-duplicates extraDeps', () => {
    expect(
      pubspecYaml(baseConfig, ['camera: ^0.10.6+2', 'camera: ^0.10.6+2']),
    ).toResemble(EXTRA_CAMERA);
  });

  it('works with no extraDeps (backward compatible)', () => {
    expect(pubspecYaml(baseConfig)).toResemble(BASE);
  });
});

describe('pubspecYaml — assets', () => {
  it('emits flutter assets section when config.assets is non-empty', () => {
    const config: AppConfig = {
      ...baseConfig,
      assets: ['assets/config.json', 'assets/images/'],
    };
    expect(pubspecYaml(config)).toResemble(ASSETS);
  });

  it('does not emit assets section when config.assets is empty', () => {
    expect(pubspecYaml({ ...baseConfig, assets: [] })).toResemble(BASE);
  });

  it('does not emit assets section when config.assets is undefined', () => {
    expect(pubspecYaml(baseConfig)).toResemble(BASE);
  });
});

describe('pubspecYaml — brand assets (DetectedAssets)', () => {
  it('default ({}) → no mention of flutter_launcher_icons or flutter_native_splash', () => {
    expect(pubspecYaml(baseConfig)).toResemble(BASE);
  });

  it('icon: true → emits flutter_launcher_icons dev dep and config block', () => {
    expect(pubspecYaml(baseConfig, [], { assets: { icon: true } })).toResemble(
      ICON,
    );
  });

  it('icon: true → cascades to flutter_native_splash with icon.png as image', () => {
    expect(pubspecYaml(baseConfig, [], { assets: { icon: true } })).toResemble(
      ICON,
    );
  });

  it('splash: true (no icon) → only flutter_native_splash with splash.png', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { splash: true } }),
    ).toResemble(SPLASH);
  });

  it('icon + splash → splash engine uses splash.png (not cascaded icon)', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { icon: true, splash: true } }),
    ).toResemble(ICON_SPLASH);
  });

  it('icon + background → adaptive_icon_background uses background.png, not #ffffff', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { icon: true, background: true } }),
    ).toResemble(ICON_BG);
  });

  it('icon only (no background) → adaptive_icon_background defaults to #ffffff', () => {
    expect(pubspecYaml(baseConfig, [], { assets: { icon: true } })).toResemble(
      ICON,
    );
  });

  it('icon + monochrome → adaptive_icon_monochrome present', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { icon: true, monochrome: true } }),
    ).toResemble(ICON_MONO);
  });

  it('icon + iconDark → image_path_dark present in launcher block', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { icon: true, iconDark: true } }),
    ).toResemble(ICON_ICONDARK);
  });

  it('icon + backgroundDark → adaptive_icon_background_dark present', () => {
    expect(
      pubspecYaml(baseConfig, [], {
        assets: { icon: true, backgroundDark: true },
      }),
    ).toResemble(ICON_BGDARK);
  });

  it('icon + monochromeDark → adaptive_icon_monochrome_dark present', () => {
    expect(
      pubspecYaml(baseConfig, [], {
        assets: { icon: true, monochromeDark: true },
      }),
    ).toResemble(ICON_MONODARK);
  });

  it('icon + splashDark → image_dark present in splash block', () => {
    expect(
      pubspecYaml(baseConfig, [], { assets: { icon: true, splashDark: true } }),
    ).toResemble(ICON_SPLASHDARK);
  });

  it('icon + backgroundDark → background_image_dark present in splash block', () => {
    expect(
      pubspecYaml(baseConfig, [], {
        assets: { icon: true, backgroundDark: true },
      }),
    ).toResemble(ICON_BGDARK);
  });

  it('all 8 keys true → all light + dark blocks present', () => {
    const all: DetectedAssets = {
      icon: true,
      splash: true,
      background: true,
      monochrome: true,
      iconDark: true,
      splashDark: true,
      backgroundDark: true,
      monochromeDark: true,
    };
    expect(pubspecYaml(baseConfig, [], { assets: all })).toResemble(ALL8);
  });

  it('existing call sites unchanged when third arg omitted', () => {
    expect(pubspecYaml(baseConfig, ['provider: ^6.0.0'])).toResemble(
      EXTRA_PROVIDER,
    );
  });
});

describe('pubspecYaml — legal assets', () => {
  it('includes privacy.md in flutter assets when legal.privacy is true', () => {
    expect(
      pubspecYaml(baseConfig, [], { legal: { privacy: true } }),
    ).toResemble(LEGAL_PRIVACY);
  });

  it('includes both legal files when present', () => {
    expect(
      pubspecYaml(baseConfig, [], { legal: { privacy: true, terms: true } }),
    ).toResemble(LEGAL_BOTH);
  });

  it('omits legal files when neither flag is true', () => {
    expect(
      pubspecYaml(baseConfig, [], { legal: { privacy: false, terms: false } }),
    ).toResemble(BASE);
  });
});

describe('pubspecYaml — fonts', () => {
  it('default (no fonts arg) → no flutter: fonts: block', () => {
    expect(pubspecYaml(baseConfig)).toResemble(BASE);
  });

  it('emits a fonts block for a single family', () => {
    const fonts: FontMap = {
      Inter: [{ weight: 400, italic: false, file: 'Inter-Regular.ttf' }],
    };
    expect(pubspecYaml(baseConfig, [], { fonts })).toResemble(FONTS_ONE);
  });

  it('emits two family entries in alphabetical order', () => {
    const fonts: FontMap = {
      JetBrainsMono: [
        { weight: 400, italic: false, file: 'JetBrainsMono-Regular.ttf' },
      ],
      Inter: [{ weight: 400, italic: false, file: 'Inter-Regular.ttf' }],
    };
    const out = pubspecYaml(baseConfig, [], { fonts });
    const interIdx = out.indexOf('- family: Inter');
    const jbIdx = out.indexOf('- family: JetBrainsMono');
    expect(interIdx).toBeGreaterThan(-1);
    expect(jbIdx).toBeGreaterThan(interIdx);
  });
});
