#!/usr/bin/env bun
/**
 * generate-types.ts
 *
 * Reads ref/widgets.json + ref/features.json and generates:
 *   src/generated/widget-interfaces.ts
 *   src/generated/widget-components.ts
 *   src/generated/widget-map.ts
 *   src/generated/slot-map.ts
 *   src/generated/feature-hooks.ts
 *   types/jsx.d.ts
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");

interface PropDef {
  name: string;
  tsxProp: string;
  dartParam: string;
  dartType: string;
  required: boolean;
  transform: string;
}

interface StylingDef {
  name: string;
  tsxProp: string;
  dartParam: string;
  dartType: string;
  transform: string;
}

interface WidgetDef {
  name: string;
  dartClass: string;
  category: string;
  selfSlot: string;
  defaultChildSlot: string;
  singleChild: boolean;
  props: PropDef[];
  styling: StylingDef[];
}

interface FeatureFunctionArg {
  name: string;
  tsType: string;
  dartType: string;
  required: boolean;
}

interface FeatureFunction {
  name: string;
  args: FeatureFunctionArg[];
  returns: string;
  behavior: string;
}

interface FeatureDef {
  name: string;
  dartPackage: string;
  pubspecDep: string;
  tsxHook: string;
  functions: FeatureFunction[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ensure(dir: string) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function write(filePath: string, content: string) {
  ensure(dirname(filePath));
  writeFileSync(filePath, content, "utf-8");
  console.log(`  Written: ${filePath.replace(ROOT + "/", "")}`);
}

function dartTypeToTs(dartType: string): string {
  const t = dartType.replace(/\?$/, "");
  const map: Record<string, string> = {
    "String": "string",
    "bool": "boolean",
    "int": "number",
    "double": "number",
    "VoidCallback": "() => void",
    "dynamic": "unknown",
    "Widget": "FlutterElement",
    "List<Widget>": "FlutterElement[]",
    "IconData": "string",
    "Color": "string",
    "EdgeInsetsGeometry": "number | [number, number] | [number, number, number, number]",
    "AlignmentGeometry": "string",
    "TextStyle": "TextStyleProps",
    "ThemeData": "Record<string, unknown>",
    "Axis": "'horizontal' | 'vertical'",
    "MainAxisAlignment": "'start' | 'end' | 'center' | 'spaceBetween' | 'spaceAround' | 'spaceEvenly'",
    "CrossAxisAlignment": "'start' | 'end' | 'center' | 'stretch' | 'baseline'",
    "MainAxisSize": "'min' | 'max'",
    "TextAlign": "'left' | 'right' | 'center' | 'justify' | 'start' | 'end'",
    "TextOverflow": "'clip' | 'fade' | 'ellipsis' | 'visible'",
    "BoxFit": "'fill' | 'contain' | 'cover' | 'fitWidth' | 'fitHeight' | 'none' | 'scaleDown'",
    "FontWeight": "'normal' | 'bold' | 'w100' | 'w200' | 'w300' | 'w400' | 'w500' | 'w600' | 'w700' | 'w800' | 'w900'",
    "TextInputType": "'text' | 'number' | 'phone' | 'email' | 'url' | 'multiline'",
    "StackFit": "'loose' | 'expand' | 'passthrough'",
    "FlexFit": "'tight' | 'loose'",
    "WrapAlignment": "'start' | 'end' | 'center' | 'spaceBetween' | 'spaceAround' | 'spaceEvenly'",
    "Clip": "'none' | 'hardEdge' | 'antiAlias' | 'antiAliasWithSaveLayer'",
    "ThemeMode": "'system' | 'light' | 'dark'",
  };

  if (t.startsWith("ValueChanged<")) {
    const inner = t.slice(13, -1);
    return `(value: ${dartTypeToTs(inner)}) => void`;
  }

  return map[t] ?? "unknown";
}

function propToTsOptional(prop: PropDef): string {
  const tsType = dartTypeToTs(prop.dartType);
  const optional = prop.required ? "" : "?";
  return `  ${prop.tsxProp}${optional}: ${tsType};`;
}

function childrenPropLine(widget: WidgetDef): string {
  if (widget.defaultChildSlot === "none") {
    if (widget.name === "Text") return "  children?: string | number;";
    return "";
  }
  // Always allow arrays: even "single-child" widgets (e.g. Scaffold.body) can
  // appear alongside slotted siblings (e.g. AppBar) in the same JSX block,
  // which makes TypeScript pass children as an array via jsxs().
  return "  children?: FlutterElement | FlutterElement[];";
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

function genWidgetInterfaces(widgets: WidgetDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import type { FlutterElement } from '../core/widget-node.js';`,
    ``,
    `export interface TextStyleProps {`,
    `  color?: string;`,
    `  fontSize?: number;`,
    `  fontWeight?: 'normal' | 'bold' | 'w100' | 'w200' | 'w300' | 'w400' | 'w500' | 'w600' | 'w700' | 'w800' | 'w900';`,
    `  fontStyle?: 'normal' | 'italic';`,
    `  letterSpacing?: number;`,
    `  wordSpacing?: number;`,
    `  decoration?: 'none' | 'underline' | 'overline' | 'lineThrough';`,
    `  height?: number;`,
    `  fontFamily?: string;`,
    `}`,
    ``,
  ];

  for (const widget of widgets) {
    lines.push(`export interface ${widget.name}Props {`);

    for (const prop of widget.props) {
      lines.push(propToTsOptional(prop));
    }

    for (const style of widget.styling) {
      lines.push(`  /** style.${style.name} */`);
      lines.push(`  '${style.tsxProp}'?: ${dartTypeToTs(style.dartType)};`);
    }

    const childLine = childrenPropLine(widget);
    if (childLine) lines.push(childLine);

    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
}

function genWidgetComponents(widgets: WidgetDef[]): string {
  const names = widgets.map((w) => w.name);
  const importInterfaces = names.map((n) => `${n}Props`).join(",\n  ");

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import { defineComponent } from '../core/define-component.js';`,
    `import type {`,
    `  ${importInterfaces}`,
    `} from './widget-interfaces.js';`,
    ``,
  ];

  for (const widget of widgets) {
    lines.push(`export const ${widget.name} = defineComponent<${widget.name}Props>({ single: '${widget.dartClass}' });`);
  }

  return lines.join("\n") + "\n";
}

function genWidgetMap(widgets: WidgetDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    ``,
    `export interface WidgetDef {`,
    `  name: string;`,
    `  dartClass: string;`,
    `  category: string;`,
    `  selfSlot: string;`,
    `  defaultChildSlot: string;`,
    `  singleChild: boolean;`,
    `  props: PropDef[];`,
    `  styling: StylingDef[];`,
    `}`,
    ``,
    `export interface PropDef {`,
    `  name: string;`,
    `  tsxProp: string;`,
    `  dartParam: string;`,
    `  dartType: string;`,
    `  required: boolean;`,
    `  transform: string;`,
    `}`,
    ``,
    `export interface StylingDef {`,
    `  name: string;`,
    `  tsxProp: string;`,
    `  dartParam: string;`,
    `  dartType: string;`,
    `  transform: string;`,
    `}`,
    ``,
    `export const WIDGET_MAP: Map<string, WidgetDef> = new Map([`,
  ];

  for (const widget of widgets) {
    lines.push(`  ['${widget.name}', ${JSON.stringify(widget)}],`);
  }

  lines.push(`]);`);
  lines.push(``);

  return lines.join("\n");
}

function genSlotMap(widgets: WidgetDef[]): string {
  const selfSlots = widgets.filter((w) => w.selfSlot);
  const childSlots = widgets.filter((w) => w.defaultChildSlot && w.defaultChildSlot !== "none");

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    ``,
    `/**`,
    ` * SELF_SLOT_MAP: when a widget appears as a child, which named param does it use in its parent?`,
    ` * e.g., AppBar → 'appBar' means: Scaffold(appBar: AppBar(...))`,
    ` */`,
    `export const SELF_SLOT_MAP: Map<string, string> = new Map([`,
  ];

  for (const w of selfSlots) {
    lines.push(`  ['${w.name}', '${w.selfSlot}'],`);
  }

  lines.push(`]);`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * CHILD_SLOT_MAP: which named param holds the children of this widget?`);
  lines.push(` * e.g., Center → 'child', Column → 'children', MaterialApp → 'home'`);
  lines.push(` */`);
  lines.push(`export const CHILD_SLOT_MAP: Map<string, string> = new Map([`);

  for (const w of childSlots) {
    lines.push(`  ['${w.name}', '${w.defaultChildSlot}'],`);
  }

  lines.push(`]);`);
  lines.push(``);

  const singleChildWidgets = widgets.filter((w) => w.singleChild);
  lines.push(`/** Widgets that accept only a single child */`);
  lines.push(`export const SINGLE_CHILD_WIDGETS: Set<string> = new Set([`);
  for (const w of singleChildWidgets) {
    lines.push(`  '${w.name}',`);
  }
  lines.push(`]);`);
  lines.push(``);

  return lines.join("\n");
}

function genFeatureHooks(features: FeatureDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `// Stub hooks for Flutter native features.`,
    `// Analyzed by the transpiler to generate the correct Dart plugin calls.`,
    ``,
  ];

  for (const feature of features) {
    const hookName = feature.tsxHook;
    const apiName = `${capitalize(feature.name)}API`;

    lines.push(`// ── ${capitalize(feature.name)} ──────────────────────────────────────────`);
    lines.push(`export interface ${apiName} {`);
    for (const fn of feature.functions) {
      const params = fn.args
        .map((a) => `${a.name}${a.required ? "" : "?"}: ${a.tsType}`)
        .join(", ");
      lines.push(`  /** ${fn.behavior} */`);
      lines.push(`  ${fn.name}(${params}): ${fn.returns};`);
    }
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function ${hookName}(): ${apiName} {`);
    lines.push(`  // Runtime stub — transpiler converts this to Flutter plugin calls`);
    lines.push(`  return {`);
    for (const fn of feature.functions) {
      const params = fn.args.map((a) => `_${a.name}`).join(", ");
      if (fn.returns.startsWith("Promise<")) {
        lines.push(`    ${fn.name}(${params}) { return Promise.resolve(undefined as never); },`);
      } else if (fn.returns === "() => void") {
        lines.push(`    ${fn.name}(${params}) { return () => {}; },`);
      } else {
        lines.push(`    ${fn.name}(${params}) { return undefined as never; },`);
      }
    }
    lines.push(`  } as ${apiName};`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
}

function genJsxDts(widgets: WidgetDef[]): string {
  const importLine = widgets.map((w) => `${w.name}Props`).join(",\n  ");

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import type {`,
    `  ${importLine}`,
    `} from '../src/generated/widget-interfaces.js';`,
    ``,
    `declare global {`,
    `  namespace JSX {`,
    `    interface Element extends import('../src/core/widget-node.js').WidgetNode {}`,
    `    interface IntrinsicElements {`,
  ];

  for (const widget of widgets) {
    lines.push(`      ${widget.name}: ${widget.name}Props;`);
  }

  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function run(): Promise<void> {
  const widgetsPath = join(ROOT, "ref", "widgets.json");
  const featuresPath = join(ROOT, "ref", "features.json");
  const generatedDir = join(ROOT, "src", "generated");
  const typesDir = join(ROOT, "types");

  ensure(generatedDir);
  ensure(typesDir);

  if (!existsSync(widgetsPath)) {
    throw new Error("ref/widgets.json not found — run `fsx define` first");
  }

  const widgets: WidgetDef[] = JSON.parse(readFileSync(widgetsPath, "utf-8"));
  const features: FeatureDef[] = existsSync(featuresPath)
    ? JSON.parse(readFileSync(featuresPath, "utf-8"))
    : [];

  write(join(generatedDir, "widget-interfaces.ts"), genWidgetInterfaces(widgets));
  write(join(generatedDir, "widget-components.ts"), genWidgetComponents(widgets));
  write(join(generatedDir, "widget-map.ts"), genWidgetMap(widgets));
  write(join(generatedDir, "slot-map.ts"), genSlotMap(widgets));
  write(join(generatedDir, "feature-hooks.ts"), genFeatureHooks(features));
  write(join(typesDir, "jsx.d.ts"), genJsxDts(widgets));

  console.log(`  Generated ${widgets.length} widget types + ${features.length} feature hooks`);
}

if (import.meta.main) {
  run().catch(console.error);
}
