#!/usr/bin/env bun
/**
 * generate-types.ts
 *
 * Reads ref/derived/widgets.json + ref/derived/hooks.json and generates:
 *   src/generated/widget-interfaces.ts
 *   src/generated/widget-components.ts
 *   src/generated/widget-map.ts
 *   src/generated/slot-map.ts
 *   src/generated/feature-hooks.ts
 *   types/jsx.d.ts
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type {
  FunctionDef,
  HookDef,
  PluginDef,
  PropDef,
  WidgetDef,
} from './define/api-types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ensure(dir: string) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function write(filePath: string, content: string) {
  ensure(dirname(filePath));
  writeFileSync(filePath, content, 'utf-8');
  console.log(`  Written: ${filePath.replace(ROOT + '/', '')}`);
}

// The transpiler wraps a string assigned to a Widget-typed prop in `Text(...)`
// (see codegen `transform === 'widget'`), so a widget prop accepts a string
// convenience in addition to a FlutterElement. Array widget props (e.g.
// `actions: FlutterElement[]`) are not widened — you pass elements, not a string.
const tsTypeFor = (prop: PropDef): string =>
  prop.transform === 'widget' && prop.tsType === 'FlutterElement'
    ? 'string | FlutterElement'
    : prop.tsType;

const propToTsOptional = (prop: PropDef, forceOptional = false): string => {
  const optional = forceOptional || !prop.required ? '?' : '';
  return `  ${prop.tsxProp}${optional}: ${tsTypeFor(prop)};`;
};

function childrenPropLine(widget: WidgetDef): string {
  if (widget.defaultChildSlot === 'none') {
    if (widget.name === 'Text') return '  children?: string | number;';
    return '';
  }
  // Always allow arrays: even "single-child" widgets (e.g. Scaffold.body) can
  // appear alongside slotted siblings (e.g. AppBar) in the same JSX block,
  // which makes TypeScript pass children as an array via jsxs().
  return '  children?: FlutterElement | FlutterElement[];';
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

function genWidgetInterfaces(widgets: WidgetDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import type { FlutterElement } from '../core/widget-node.js';`,
    ``,
    `export interface TextStyleProps {`,
    `  color?: string;`,
    `  fontSize?: number;`,
    `  fontWeight?: 'normal' | 'bold' | 'w100' | 'w200' | 'w300' | 'w400' | 'w500' | 'w600' | 'w700' | 'w800' | 'w900';`,
    `  fontStyle?: 'normal' | 'italic';`,
    `  letterSpacing?: number;`,
    `  wordSpacing?: number;`,
    `  decoration?: 'none' | 'underline' | 'overline' | 'lineThrough';`,
    `  height?: number;`,
    `  fontFamily?: string;`,
    `}`,
    ``,
  ];

  for (const widget of widgets) {
    lines.push(`export interface ${widget.name}Props {`);

    for (const prop of widget.props) {
      // The default-child-slot prop (e.g. AppBar.title) can also be supplied via
      // JSX children, so it must be OPTIONAL — but it is still exposed as a prop
      // so the attribute form (`<AppBar title="My App" />`, the README example)
      // type-checks. Previously it was dropped entirely, breaking that usage.
      const isDefaultSlot = prop.name === widget.defaultChildSlot;
      // When the slot prop is literally named `children` (e.g. Column.children),
      // the canonical `children?` line below already covers it — skip to avoid a
      // duplicate `children` member.
      if (isDefaultSlot && prop.tsxProp === 'children') continue;
      // Text.data is supplied positionally via JSX children (see
      // childrenPropLine), so it must be optional here — otherwise
      // `<Text>hi</Text>` fails to type-check ("data is missing").
      if (widget.name === 'Text' && prop.name === 'data') {
        lines.push('  data?: string;');
        continue;
      }
      lines.push(propToTsOptional(prop, isDefaultSlot));
    }

    for (const style of widget.styling) {
      lines.push(`  /** style.${style.name} */`);
      lines.push(`  '${style.tsxProp}'?: ${style.tsType};`);
    }

    const childLine = childrenPropLine(widget);
    if (childLine) lines.push(childLine);

    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

function genWidgetComponents(widgets: WidgetDef[]): string {
  const names = widgets.map((w) => w.name);
  const importInterfaces = names.map((n) => `${n}Props`).join(',\n  ');

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import { defineComponent } from '../core/define-component.js';`,
    `import type {`,
    `  ${importInterfaces}`,
    `} from './widget-interfaces.js';`,
    ``,
  ];

  for (const widget of widgets) {
    lines.push(
      `export const ${widget.name} = defineComponent<${widget.name}Props>({ single: '${widget.dartClass}' });`,
    );
  }

  return lines.join('\n') + '\n';
}

function genWidgetMap(widgets: WidgetDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    ``,
    `export interface WidgetDef {`,
    `  name: string;`,
    `  dartClass: string;`,
    `  category: string;`,
    `  selfSlot: string;`,
    `  defaultChildSlot: string;`,
    `  singleChild: boolean;`,
    `  props: PropDef[];`,
    `  styling: StylingDef[];`,
    `}`,
    ``,
    `export interface PropDef {`,
    `  name: string;`,
    `  tsxProp: string;`,
    `  dartParam: string;`,
    `  dartType: string;`,
    `  tsType: string;`,
    `  required: boolean;`,
    `  transform: string;`,
    `}`,
    ``,
    `export interface StylingDef {`,
    `  name: string;`,
    `  tsxProp: string;`,
    `  dartParam: string;`,
    `  dartType: string;`,
    `  tsType: string;`,
    `  transform: string;`,
    `}`,
    ``,
    `export const WIDGET_MAP: Map<string, WidgetDef> = new Map([`,
  ];

  for (const widget of widgets) {
    lines.push(`  ['${widget.name}', ${JSON.stringify(widget)}],`);
  }

  lines.push(`]);`);
  lines.push(``);

  return lines.join('\n');
}

function genSlotMap(widgets: WidgetDef[]): string {
  const selfSlots = widgets.filter((w) => w.selfSlot);
  const childSlots = widgets.filter(
    (w) => w.defaultChildSlot && w.defaultChildSlot !== 'none',
  );

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    ``,
    `/**`,
    ` * SELF_SLOT_MAP: when a widget appears as a child, which named param does it use in its parent?`,
    ` * e.g., AppBar → 'appBar' means: Scaffold(appBar: AppBar(...))`,
    ` */`,
    `export const SELF_SLOT_MAP: Map<string, string> = new Map([`,
  ];

  for (const w of selfSlots) {
    lines.push(`  ['${w.name}', '${w.selfSlot}'],`);
  }

  lines.push(`]);`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(
    ` * CHILD_SLOT_MAP: which named param holds the children of this widget?`,
  );
  lines.push(
    ` * e.g., Center → 'child', Column → 'children', MaterialApp → 'home'`,
  );
  lines.push(` */`);
  lines.push(`export const CHILD_SLOT_MAP: Map<string, string> = new Map([`);

  for (const w of childSlots) {
    lines.push(`  ['${w.name}', '${w.defaultChildSlot}'],`);
  }

  lines.push(`]);`);
  lines.push(``);

  const singleChildWidgets = widgets.filter((w) => w.singleChild);
  lines.push(`/** Widgets that accept only a single child */`);
  lines.push(`export const SINGLE_CHILD_WIDGETS: Set<string> = new Set([`);
  for (const w of singleChildWidgets) {
    lines.push(`  '${w.name}',`);
  }
  lines.push(`]);`);
  lines.push(``);

  return lines.join('\n');
}

function genFeatureHooks(features: HookDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `// Stub hooks for Flutter native features.`,
    `// Analyzed by the transpiler to generate the correct Dart plugin calls.`,
    ``,
  ];

  for (const feature of features) {
    const hookName = feature.tsxHook;
    const apiName = `${capitalize(feature.name)}API`;

    lines.push(
      `// ── ${capitalize(feature.name)} ──────────────────────────────────────────`,
    );
    lines.push(`export interface ${apiName} {`);
    for (const fn of feature.functions) {
      const params = fn.args
        .map((a) => `${a.name}${a.required ? '' : '?'}: ${a.tsType}`)
        .join(', ');
      lines.push(`  /** ${fn.behavior} */`);
      lines.push(`  ${fn.name}(${params}): ${fn.returns};`);
    }
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function ${hookName}(): ${apiName} {`);
    lines.push(
      `  // Runtime stub — transpiler converts this to Flutter plugin calls`,
    );
    lines.push(`  return {`);
    for (const fn of feature.functions) {
      const params = fn.args.map((a) => `_${a.name}`).join(', ');
      if (fn.returns.startsWith('Promise<')) {
        lines.push(
          `    ${fn.name}(${params}) { return Promise.resolve(undefined as never); },`,
        );
      } else if (fn.returns === '() => void') {
        lines.push(`    ${fn.name}(${params}) { return () => {}; },`);
      } else {
        lines.push(`    ${fn.name}(${params}) { return undefined as never; },`);
      }
    }
    lines.push(`  } as ${apiName};`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

function genJsxDts(widgets: WidgetDef[]): string {
  const importLine = widgets.map((w) => `${w.name}Props`).join(',\n  ');

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `import type {`,
    `  ${importLine}`,
    `} from '../src/generated/widget-interfaces.js';`,
    ``,
    `declare global {`,
    `  namespace JSX {`,
    `    interface Element extends import('../src/core/widget-node.js').WidgetNode {}`,
    `    interface IntrinsicElements {`,
  ];

  for (const widget of widgets) {
    lines.push(`      ${widget.name}: ${widget.name}Props;`);
  }

  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function genFeatureFunctions(functions: FunctionDef[]): string {
  if (functions.length === 0) {
    return `// DO NOT EDIT — generated by \`fsx define\`\n// No utility functions registered yet.\n`;
  }

  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    `// Utility functions that map to Dart SDK statics or single-call plugin APIs.`,
    ``,
  ];

  // Separate plain functions from namespaced ones (e.g. "hapticFeedback.light")
  const plain = functions.filter((f) => !f.name.includes('.'));
  const namespaced = functions.filter((f) => f.name.includes('.'));

  for (const fn of plain) {
    const params = fn.args
      .map((a) => `${a.name}${a.required ? '' : '?'}: ${a.tsType}`)
      .join(', ');
    lines.push(`/** ${fn.description} */`);
    lines.push(`export function ${fn.name}(${params}): ${fn.returns} {`);
    lines.push(`  // Runtime stub — transpiler rewrites to Dart`);
    lines.push(`  return undefined as never;`);
    lines.push(`}`);
    lines.push(``);
  }

  // Group namespaced functions into const objects
  const groups = new Map<string, FunctionDef[]>();
  for (const fn of namespaced) {
    const ns = fn.name.split('.')[0]!;
    const group = groups.get(ns) ?? [];
    group.push(fn);
    groups.set(ns, group);
  }

  for (const [ns, fns] of groups) {
    lines.push(`export const ${ns} = {`);
    for (const fn of fns) {
      const method = fn.name.split('.').slice(1).join('.');
      const params = fn.args
        .map((a) => `${a.name}${a.required ? '' : '?'}: ${a.tsType}`)
        .join(', ');
      lines.push(`  /** ${fn.description} */`);
      lines.push(`  ${method}(${params}): ${fn.returns} {`);
      lines.push(`    // Runtime stub — transpiler rewrites to Dart`);
      lines.push(`    return undefined as never;`);
      lines.push(`  },`);
    }
    lines.push(`};`);
    lines.push(``);
  }

  return lines.join('\n');
}

function genPluginMap(plugins: PluginDef[]): string {
  const lines: string[] = [
    `// DO NOT EDIT — generated by \`fsx define\``,
    ``,
    `export interface PluginDef {`,
    `  name: string;`,
    `  domain: string;`,
    `  surface: string;`,
    `  tsxName: string;`,
    `  description: string;`,
    `  package?: string;`,
    `  pubspecDep?: string;`,
    `  dartImport: string;`,
    `  tsxExample: string;`,
    `  dartExample: string;`,
    `}`,
    ``,
    `export const PLUGIN_MAP: Map<string, PluginDef> = new Map([`,
  ];

  for (const plugin of plugins) {
    lines.push(
      `  [${JSON.stringify(plugin.tsxName)}, ${JSON.stringify(plugin)}],`,
    );
  }

  lines.push(`]);`);
  lines.push(``);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function run(): Promise<void> {
  const widgetsPath = join(ROOT, 'ref', 'derived', 'widgets.json');
  const featuresPath = join(ROOT, 'ref', 'derived', 'hooks.json');
  const functionsPath = join(ROOT, 'ref', 'derived', 'functions.json');
  const pluginsPath = join(ROOT, 'ref', 'derived', 'plugins.json');
  const generatedDir = join(ROOT, 'src', 'generated');
  const typesDir = join(ROOT, 'types');

  ensure(generatedDir);
  ensure(typesDir);

  if (!existsSync(widgetsPath)) {
    throw new Error(
      'ref/derived/widgets.json not found — run `fsx define` first',
    );
  }

  const widgets: WidgetDef[] = JSON.parse(readFileSync(widgetsPath, 'utf-8'));
  const features: HookDef[] = existsSync(featuresPath)
    ? JSON.parse(readFileSync(featuresPath, 'utf-8'))
    : [];
  const functions: FunctionDef[] = existsSync(functionsPath)
    ? JSON.parse(readFileSync(functionsPath, 'utf-8'))
    : [];
  const plugins: PluginDef[] = existsSync(pluginsPath)
    ? JSON.parse(readFileSync(pluginsPath, 'utf-8'))
    : [];

  write(
    join(generatedDir, 'widget-interfaces.ts'),
    genWidgetInterfaces(widgets),
  );
  write(
    join(generatedDir, 'widget-components.ts'),
    genWidgetComponents(widgets),
  );
  write(join(generatedDir, 'widget-map.ts'), genWidgetMap(widgets));
  write(join(generatedDir, 'slot-map.ts'), genSlotMap(widgets));
  write(join(generatedDir, 'feature-hooks.ts'), genFeatureHooks(features));
  write(
    join(generatedDir, 'feature-functions.ts'),
    genFeatureFunctions(functions),
  );
  write(join(generatedDir, 'plugin-map.ts'), genPluginMap(plugins));
  write(join(typesDir, 'jsx.d.ts'), genJsxDts(widgets));

  console.log(
    `  Generated ${widgets.length} widget types + ${features.length} feature hooks + ${functions.length} utility functions`,
  );
}

if (import.meta.main) {
  run().catch((err: unknown) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
